# Generated by Django 2.2.7 on 2019-11-12 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_registration',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
