# Generated by Django 2.2.7 on 2019-11-13 12:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20191113_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.User')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('product', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
